//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notebook
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoteModel
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public string Theme { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<System.DateTime> FinishTime { get; set; }
        public string Place { get; set; }
        public string Result { get; set; }
    }
}
